### ISSUE TITLE
back-propagation issue

### ISSUE THREAD

**Issue by zhan-xu** [banctilrobitaille/torch-vectorized#5]
Thanks for the code. I am trying to use it to accelerate eigen decomposition. My input matrices are in shape (B, 3 ,3). To apply vSymEig, I first reshape it into (B, 9), and then expand the dimension to (B, 9, 1, 1, 1), and pass it through vSymEig. Finally I unsqueeze the output to return back to (B, 3) and (B, 3, 3). The code is as follows:

```
A_flat = A.reshape(-1, 9)[..., None, None, None]
w, v = vSymEig(A_flat, eigen_vectors=True)
w = w.squeeze()
v = v.squeeze()
```

However when I run later loss.backward(), this piece of code gives me error as follows:

```
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.DoubleTensor [10900, 3, 1, 1, 1]], which is output 0 of SqrtBackward, is at version 1; expected version 0 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).
```

Do you happen to meet similar problem, or any suggestions?

**Comment by zhan-xu** [comment]
Maybe it is not about the shape. Here is a bit more information. I tried the following code

```
import torch
from torchvectorized.utils import sym
from torchvectorized.vlinalg import vSymEig

# Random batch of volumetric 3x3 symmetric matrices of size 16x9x32x32x32
input = sym(torch.rand(16, 9, 32, 32, 32))
input.requires_grad=True

# Output eig_vals with size: 16x3x32x32x32 and eig_vecs with size 16,3,3,32,32,32
eig_vals, eig_vecs = vSymEig(input, eigen_vectors=True)

gt_vals = torch.randn((16, 3, 32, 32, 32))
gt_vecs = torch.randn((16, 3, 3, 32, 32, 32))

#loss = torch.nn.functional.mse_loss(eig_vals, gt_vals) # this line goes without error
loss = torch.nn.functional.mse_loss(eig_vecs, gt_vecs) # this line has error
loss.backward()
```

The problem seems happen when we add supervision to the eig_vecs.

**Comment by zhan-xu** [comment]
The problem is perhaps related to https://github.com/banctilrobitaille/torch-vectorized/blob/master/torchvectorized/vlinalg.py#L55
When commenting out line 56, it works. btw why here do you replace 0 with 1? Shouldn't replace it with a small number like 1e-10?

**Comment by zhan-xu** [comment]
As a walk-round, I change line 56 into 
```
u0 = u0 / (norm+1e-10)
u1 = u1 / (norm+1e-10)
u2 = u2 / (norm+1e-10)
```
Seems working so far...

**Comment by banctilrobitaille** [comment]
Hello @zhan-xu , sorry for my late reply. I fixed the backprop for the vSymEig function by:

- Removing the inplace operation on the norm
- Adding an Epsilon value in the square root of the norm computation to avoid undefined gradients at 0.

I did an optimization test using an Adam optimizer and an L1 loss on the eigenvalues and eigenvectors and it looks good now:
![optimization](https://user-images.githubusercontent.com/5373064/105254025-a6dcd880-5b4e-11eb-92a1-82a5b3956f7c.png)`
